import Head from "next/head";
import Image from "next/image";
import styles from "../styles/components/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fluid Aesthetics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Fluid <a href="https://nextjs.org">Aesthetics</a>
        </h1>

        <div className={styles.grid}>
          <Link href="/about" className={styles.card} >
            <a>
              <article className={styles.card}>
                <h2>About Fluid Aesthetics&rarr;</h2>
                <p>
               Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque odit earum ea quisquam vitae autem consequuntur illo, commodi ipsa! Pariatur id aspernatur quidem nobis facere in praesentium ullam obcaecati hic?
                </p>
              </article>
            </a>
          </Link>

          {/* <Link href="/book-consult" className={styles.card}>
            <a>
              <article className={styles.card}>
                <h2>Book a consultation&rarr;</h2>
                <p>
           Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum recusandae est laudantium eos asperiores, iste corrupti debitis numquam voluptatum quas, vitae saepe. Eveniet odit sint eum tenetur maiores accusamus dolorum!
                </p>
              </article>
            </a>
          </Link> */}
          {/* <Link href="/faq">
            <a>
              <article className={styles.card}>
                <h2>FAQ&rarr;</h2>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sequi, distinctio. Maxime eum ad pariatur accusamus. Laboriosam, dolorem ipsam eos ea animi, natus optio laudantium illum sapiente earum doloribus nesciunt cumque?</p>
              </article>
            </a>
          </Link> */}
          {/* <Link href="/staff-bios">
            <a>
              <article className={styles.card}>
                <h2>Staff Bios&rarr;</h2>
                <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quod minus cumque, officiis dicta, quam dolorum delectus praesentium, porro libero natus suscipit veniam inventore voluptas veritatis quaerat? Repudiandae recusandae cumque beatae!
                </p>
              </article>
            </a>
          </Link> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://joaquinfox.github.io/profile//"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by JoaquinFox.com
        </a>
      </footer>
    </div>
  );
}
