import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fluid Aesthetics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Fluid <a href="https://nextjs.org">Aesthetics</a>
        </h1>

        <div className={styles.grid}>
          <Link href="/about">
            <a>
              <article className={styles.card}>
                <h2>About Fluid Aesthetics&rarr;</h2>
                <p>
                  Lorem, lorem ipsum dolor sit amet consectetur adipisicing
                  elit.{" "}
                </p>
              </article>
            </a>
          </Link>

          <Link href="/book-consult">
            <a>
              <article className={styles.card}>
                <h2>Book a consultation&rarr;</h2>
                <p>
                  sit amet consectetur adipisicing elit. Lorem ire qui nam
                  temporibus sit a, voluptate assumenda placeat corporis cum
                  esse quo ab.
                </p>
              </article>
            </a>
          </Link>
          <Link href="/faq">
            <a>
              <article className={styles.card}>
                <h2>FAQ&rarr;</h2>
                <p>l Ad consectetur suscipit laboriosam tempore illo?</p>
              </article>
            </a>
          </Link>
          <Link href="/staff-bios">
            <a>
              <article className={styles.card}>
                <h2>Staff Bios&rarr;</h2>
                <p>
                  {" "}
                  ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem
                  accusamus sit ipsa audantium rem culpa.
                </p>
              </article>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://joaquinfox.github.io/profile//"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by JoaquinFox.com
        </a>
      </footer>
    </div>
  );
}
